"""add_weight_to_variant

Revision ID: 27b6e3080fdb
Revises: 618afba15ad3
Create Date: 2026-01-03 11:21:06.022200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b6e3080fdb'
down_revision: Union[str, Sequence[str], None] = '618afba15ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('weight_grams', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'weight_grams')
    # ### end Alembic commands ###
