"""change_price_type_to_string

Revision ID: 725aaa01f650
Revises: cf90372a469a
Create Date: 2026-01-03 11:27:55.486145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '725aaa01f650'
down_revision: Union[str, Sequence[str], None] = 'cf90372a469a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price', 'price_type',
               existing_type=postgresql.ENUM('RETAIL', 'WHOLESALE', name='pricetype'),
               type_=sa.String(),
               nullable=False)
    op.alter_column('price', 'value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price', 'value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('price', 'price_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('RETAIL', 'WHOLESALE', name='pricetype'),
               nullable=True)
    # ### end Alembic commands ###
